export default function InsightsPanel({ insights }) {
  if (!insights || insights.length === 0) {
    return null
  }

  const categoryColors = {
    trend: 'var(--accent-indigo)',
    anomaly: 'var(--accent-rose)',
    pattern: 'var(--accent-cyan)',
    recommendation: 'var(--accent-emerald)',
  }

  return (
    <div className="report-section">
      <div className="section-header">
        <h2 className="section-title">💡 AI Business Insights</h2>
        <p className="section-subtitle">{insights.length} insights generated by the Insight Agent</p>
      </div>
      <div className="insight-list">
        {insights.map((insight, i) => (
          <div
            key={i}
            className={`insight-item ${insight.category || 'pattern'}`}
            style={{ animationDelay: `${i * 0.1}s` }}
          >
            <div
              className="insight-category"
              style={{ color: categoryColors[insight.category] || 'var(--text-muted)' }}
            >
              {insight.category || 'insight'}
            </div>
            <div className="insight-text">{insight.text}</div>
            {insight.metric_value && (
              <span className="insight-metric">📊 {insight.metric_value}</span>
            )}
            {insight.comparison && (
              <span className="insight-metric" style={{
                background: 'rgba(6, 182, 212, 0.1)',
                color: 'var(--accent-cyan)',
                marginLeft: '0.5rem',
              }}>
                🔄 {insight.comparison}
              </span>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
